// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const DATABASE_URL = `mysql://${process.env["DATABASE_HOST"]}:${process.env["DATABASE_PASSWORD"]}@${process.env["DATABASE_HOST"]}:${process.env["DATABASE_PORT"]}/${process.env["DATABASE_NAME"]}`;

export default defineConfig({
  schema: "src/prisma/",
  migrations: {
    path: "src/prisma/migrations",
  },
  datasource: {
    url: DATABASE_URL,
  },
});
